version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /srv/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
  caddy:
    container_name: caddy
    restart: unless-stopped
    image: abiosoft/caddy
    volumes:
      - /srv/docker/caddy/Caddyfile:/etc/Caddyfile
      - /srv/docker/caddy/cert:/root/.caddy
    networks:
      caddy:
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ACME_AGREE=TRUE
  homeassistant:
    container_name: home-assistant
    restart: unless-stopped
    image: homeassistant/home-assistant
    depends_on:
      - "caddy"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /srv/docker/hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      caddy:
    ports:
      - "8123:8123"
    privileged: true

# Postgres
#  postdb01:
#    container_name: postdb01
#    restart: unless-stopped
#    image: postgres:9.6
#    volumes:
#      - /srv/docker/postgresql:/var/lib/postgresql/data
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      - POSTGRES_USER='myusername'
#      - POSTGRES_PASSWORD='mypassword'
#    ports:
#      - "5432:5432"
# jupyter
# samba?

networks:
  caddy:
    driver: bridge
